<?php

use App\Jobs\GenerateWordAudio;
use App\Models\Word;
use App\Services\AzureTextToSpeech;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Storage;

uses(RefreshDatabase::class);

beforeEach(function () {
    Storage::fake(Word::AUDIO_DISK);

    config([
        'services.azure_speech.key' => 'test-key',
        'services.azure_speech.region' => 'southeastasia',
        'services.azure_speech.language' => 'zh-CN',
        'services.azure_speech.voice' => 'zh-CN-XiaoxiaoNeural',
    ]);
});

/**
 * Azure answers every text-to-speech request with $status (the first matching fake wins, so call it once per test).
 */
function fakeTextToSpeech(int $status = 200): void
{
    Http::fake(['*.tts.speech.microsoft.com/*' => Http::response($status === 200 ? 'mp3-bytes' : 'error', $status)]);
}

test('words saved without audio get one generated by Azure', function () {
    fakeTextToSpeech();
    $word = Word::factory()->create(['hanzi' => '行', 'pinyin_number' => 'hang2']);

    expect($word->fresh()->audio_url)->toStartWith(Word::GENERATED_AUDIO_DIRECTORY.'/')
        ->and($word->fresh()->audio_src)->toBe(Storage::disk(Word::AUDIO_DISK)->url($word->fresh()->audio_url));
    Storage::disk(Word::AUDIO_DISK)->assertExists($word->fresh()->audio_url);
    expect(Storage::disk(Word::AUDIO_DISK)->get($word->fresh()->audio_url))->toBe('mp3-bytes');

    // The pinyin pins the reading of polyphonic characters.
    Http::assertSent(fn (Request $request) => $request->url() === 'https://southeastasia.tts.speech.microsoft.com/cognitiveservices/v1'
        && $request->hasHeader('Ocp-Apim-Subscription-Key', 'test-key')
        && $request->hasHeader('X-Microsoft-OutputFormat', 'audio-24khz-48kbitrate-mono-mp3')
        && str_contains($request->body(), 'name="zh-CN-XiaoxiaoNeural"')
        && str_contains($request->body(), '<phoneme alphabet="sapi" ph="hang 2">行</phoneme>'));
});

test('multi-syllable pinyin is split into sapi phones', function () {
    fakeTextToSpeech();
    Word::factory()->create(['hanzi' => '绿茶', 'pinyin_number' => 'lü4cha2']);

    Http::assertSent(fn (Request $request) => str_contains($request->body(), 'ph="lv 4 - cha 2"'));
});

test('uploaded or linked audio is kept', function () {
    fakeTextToSpeech();
    Word::factory()->create(['audio_url' => Word::AUDIO_DIRECTORY.'/hao.mp3']);
    Word::factory()->create(['audio_url' => 'https://example.com/hao.mp3']);

    Http::assertNothingSent();
});

test('generated audio is read again when the word changes, and the old file is removed', function () {
    fakeTextToSpeech();
    $word = Word::factory()->create(['hanzi' => '行', 'pinyin_number' => 'xing2']);
    $old = $word->fresh()->audio_url;

    $word->fresh()->update(['pinyin_number' => 'hang2']);

    expect($word->fresh()->audio_url)->not->toBe($old)->toStartWith(Word::GENERATED_AUDIO_DIRECTORY.'/');
    Storage::disk(Word::AUDIO_DISK)->assertMissing($old);
    Http::assertSentCount(2);
});

test('replacing or deleting audio removes the stored file', function () {
    fakeTextToSpeech();
    $word = Word::factory()->create();
    $generated = $word->fresh()->audio_url;

    $word->fresh()->update(['audio_url' => Word::AUDIO_DIRECTORY.'/upload.mp3']);
    Storage::disk(Word::AUDIO_DISK)->assertMissing($generated);

    Storage::disk(Word::AUDIO_DISK)->put(Word::AUDIO_DIRECTORY.'/upload.mp3', 'x');
    $word->fresh()->delete();
    Storage::disk(Word::AUDIO_DISK)->assertMissing(Word::AUDIO_DIRECTORY.'/upload.mp3');
});

test('saving only queues the audio, and only when Azure is configured', function () {
    Queue::fake();
    fakeTextToSpeech();

    $word = Word::factory()->create();
    Queue::assertPushed(GenerateWordAudio::class, fn (GenerateWordAudio $job) => $job->word->is($word));
    Http::assertNothingSent();
    expect($word->fresh()->audio_url)->toBeNull();

    // Words that already have audio for everything don't queue anything.
    Word::factory()->create(['audio_url' => 'https://example.com/hao.mp3']);

    config(['services.azure_speech.key' => null]);
    Word::factory()->create();

    Queue::assertPushed(GenerateWordAudio::class, 1);
});

test('the job keeps what Azure read and fails so the rest is retried', function () {
    Queue::fake();
    $word = Word::factory()->create([
        'audio_url' => 'https://example.com/hao.mp3',
        'examples' => [['sentence' => '我很好。', 'audio_url' => null], ['sentence' => '好吃！', 'audio_url' => null]],
    ]);

    Http::fake([
        '*' => fn (Request $request) => str_contains($request->body(), '好吃') ? Http::response('error', 500) : Http::response('mp3-bytes'),
    ]);

    expect(fn () => (new GenerateWordAudio($word))->handle(app(AzureTextToSpeech::class)))->toThrow(RuntimeException::class);

    $examples = $word->fresh()->examples;
    expect($examples[0]['audio_url'])->toStartWith(Word::GENERATED_AUDIO_DIRECTORY.'/')
        ->and($examples[1]['audio_url'])->toBeNull()
        // Saved quietly: the job doesn't queue itself again.
        ->and(Queue::pushed(GenerateWordAudio::class))->toHaveCount(1);
});

test('example sentences without audio get one generated by Azure', function () {
    fakeTextToSpeech();

    $word = Word::factory()->create([
        'audio_url' => 'https://example.com/hao.mp3',
        'examples' => [
            ['sentence' => '我很好。', 'pinyin' => 'Wǒ hěn hǎo.', 'meaning' => 'Tôi rất khoẻ.', 'audio_url' => null],
            ['sentence' => '好吃！', 'pinyin' => 'Hǎochī!', 'meaning' => 'Ngon!', 'audio_url' => Word::EXAMPLE_AUDIO_DIRECTORY.'/upload.mp3'],
        ],
    ]);

    $examples = $word->fresh()->examples;
    expect($examples[0]['audio_url'])->toStartWith(Word::GENERATED_AUDIO_DIRECTORY.'/')
        ->and($examples[0]['sentence'])->toBe('我很好。')
        ->and($examples[1]['audio_url'])->toBe(Word::EXAMPLE_AUDIO_DIRECTORY.'/upload.mp3')
        ->and(Word::audioUrl($examples[0]['audio_url']))->toBe(Storage::disk(Word::AUDIO_DISK)->url($examples[0]['audio_url']));
    Storage::disk(Word::AUDIO_DISK)->assertExists($examples[0]['audio_url']);

    // Only the first sentence is read; sentences have no phoneme hint.
    Http::assertSentCount(1);
    Http::assertSent(fn (Request $request) => str_contains($request->body(), '>我很好。</voice>'));
});

test('example audio is read again when the sentence changes, and unused files are removed', function () {
    fakeTextToSpeech();

    $word = Word::factory()->create([
        'audio_url' => 'https://example.com/hao.mp3',
        'examples' => [['sentence' => '我很好。', 'audio_url' => null], ['sentence' => '好吃！', 'audio_url' => null]],
    ]);
    [$first, $second] = array_column($word->fresh()->examples, 'audio_url');

    // Unchanged sentences are not read again.
    $word->fresh()->update(['note' => 'x']);
    Http::assertSentCount(2);

    $word->fresh()->update(['examples' => [['sentence' => '我不好。', 'audio_url' => $first]]]);

    $audio = $word->fresh()->examples[0]['audio_url'];
    expect($audio)->not->toBe($first)->toStartWith(Word::GENERATED_AUDIO_DIRECTORY.'/');
    Storage::disk(Word::AUDIO_DISK)->assertExists($audio);
    Storage::disk(Word::AUDIO_DISK)->assertMissing($first);
    Storage::disk(Word::AUDIO_DISK)->assertMissing($second);

    $word->fresh()->delete();
    Storage::disk(Word::AUDIO_DISK)->assertMissing($audio);
});
