<?php

namespace App\Models;

use App\Observers\WordObserver;
use Database\Factories\WordFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * @property list<array{0: ?string, 1: string}> $meanings [part_of_speech, meaning] pairs
 * @property-read string $meaning_text
 * @property-read list<string> $part_of_speech_labels
 * @property-read ?string $image_src
 * @property-read ?string $audio_src
 * @property list<array{sentence: string, pinyin: ?string, meaning: ?string, audio_url: ?string}>|null $examples
 */
#[Fillable(['hanzi', 'traditional', 'pinyin', 'pinyin_number', 'han_viet', 'meanings', 'hsk_level', 'stroke_count', 'note', 'examples', 'audio_url', 'image_url'])]
#[ObservedBy(WordObserver::class)]
class Word extends Model
{
    /** @use HasFactory<WordFactory> */
    use HasFactory;

    public const PARTS_OF_SPEECH = [
        'noun' => 'Danh từ',
        'verb' => 'Động từ',
        'adjective' => 'Tính từ',
        'adverb' => 'Phó từ',
        'pronoun' => 'Đại từ',
        'numeral' => 'Số từ',
        'measure_word' => 'Lượng từ',
        'preposition' => 'Giới từ',
        'conjunction' => 'Liên từ',
        'particle' => 'Trợ từ',
        'interjection' => 'Thán từ',
        'phrase' => 'Cụm từ',
    ];

    /** Disk for images uploaded in the admin word form. */
    public const IMAGE_DISK = 'public';

    /** Disk and directory for audio uploaded in the admin word form. */
    public const AUDIO_DISK = 'public';

    public const AUDIO_DIRECTORY = 'words/audio';

    public const EXAMPLE_AUDIO_DIRECTORY = 'words/audio/examples';

    /** @var list<string> */
    public const AUDIO_FILE_TYPES = ['audio/mpeg', 'audio/mp4', 'audio/x-m4a', 'audio/ogg', 'audio/wav', 'audio/x-wav', 'audio/webm'];

    /** Audio generated by Azure text to speech when the admin uploads none (see WordObserver). */
    public const GENERATED_AUDIO_DIRECTORY = 'words/audio/generated';

    /**
     * Whether a stored path is a file on our disk rather than an external URL.
     */
    public static function isStoredFile(?string $path): bool
    {
        return filled($path) && ! Str::startsWith($path, ['http://', 'https://', '/']);
    }

    public static function isGeneratedAudio(?string $path): bool
    {
        return self::isStoredFile($path) && Str::startsWith($path, self::GENERATED_AUDIO_DIRECTORY.'/');
    }

    /**
     * Generated files are named after a hash of the text they read, so a changed text is read again.
     */
    public static function audioTextHash(string $text): string
    {
        return substr(sha1($text), 0, 12);
    }

    /**
     * Whether audio must be generated for $text: there is none, or it was generated for another text.
     * Audio the admin uploaded or linked is never replaced.
     */
    public static function needsGeneratedAudio(?string $path, string $text): bool
    {
        return blank($path) || (self::isGeneratedAudio($path) && ! str_contains(basename($path), self::audioTextHash($text)));
    }

    /**
     * The text read for the word's own audio; the pinyin pins the reading of polyphonic characters.
     */
    public function audioText(): string
    {
        return $this->hanzi.'|'.$this->pinyin_number;
    }

    /**
     * Audio paths/URLs of the word and its examples.
     *
     * @return list<string>
     */
    public function audioFiles(): array
    {
        return array_values(array_filter([$this->audio_url, ...array_column($this->examples ?? [], 'audio_url')]));
    }

    /**
     * Whether the word or one of its example sentences needs generated audio.
     */
    public function hasMissingAudio(): bool
    {
        return self::needsGeneratedAudio($this->audio_url, $this->audioText())
            || collect($this->examples ?? [])->contains(fn (array $example): bool => filled(trim((string) ($example['sentence'] ?? '')))
                && self::needsGeneratedAudio($example['audio_url'] ?? null, trim((string) $example['sentence'])));
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'hsk_level' => 'integer',
            'stroke_count' => 'integer',
            // Example sentences, in display order: [{sentence, pinyin, meaning, audio_url}]
            'examples' => 'array',
        ];
    }

    /**
     * Meanings as a list of [part_of_speech, meaning] pairs (JSON column); part_of_speech may be null.
     * Also accepts a single string or a list of strings (meanings without a part of speech); blank meanings are dropped.
     */
    protected function meanings(): Attribute
    {
        return Attribute::make(
            get: fn (?string $value): array => json_decode((string) $value, true) ?? [],
            set: fn (string|array|null $value): string => json_encode(
                collect(is_array($value) ? $value : [$value])
                    ->map(fn ($item): array => is_array($item) ? array_values($item) : [null, $item])
                    ->map(fn (array $item): array => [blank($item[0] ?? null) ? null : $item[0], trim((string) ($item[1] ?? ''))])
                    ->filter(fn (array $item): bool => $item[1] !== '')
                    ->values()
                    ->all(),
                JSON_UNESCAPED_UNICODE,
            ),
        );
    }

    /**
     * All meanings in one line, e.g. "tốt; khoẻ; hay". Used for display and in review quizzes.
     */
    protected function meaningText(): Attribute
    {
        return Attribute::get(fn (): string => implode('; ', array_column($this->meanings, 1)));
    }

    /**
     * Distinct parts of speech of the meanings, as Vietnamese labels, e.g. ["Tính từ"].
     */
    protected function partOfSpeechLabels(): Attribute
    {
        return Attribute::get(fn (): array => collect($this->meanings)
            ->pluck(0)
            ->filter()
            ->unique()
            ->map(fn (string $partOfSpeech): string => self::PARTS_OF_SPEECH[$partOfSpeech] ?? $partOfSpeech)
            ->values()
            ->all());
    }

    /**
     * Image URL: image_url may be a full URL or a path uploaded to the public disk.
     */
    protected function imageSrc(): Attribute
    {
        return Attribute::get(fn (): ?string => self::fileUrl($this->image_url, self::IMAGE_DISK));
    }

    /**
     * Audio URL: audio_url may be a full URL or a path (uploaded or generated) on the public disk.
     */
    protected function audioSrc(): Attribute
    {
        return Attribute::get(fn (): ?string => self::audioUrl($this->audio_url));
    }

    /**
     * URL of a word or example audio_url, which may be a full URL or a path on the audio disk.
     */
    public static function audioUrl(?string $path): ?string
    {
        return self::fileUrl($path, self::AUDIO_DISK);
    }

    private static function fileUrl(?string $path, string $disk): ?string
    {
        return match (true) {
            blank($path) => null,
            self::isStoredFile($path) => Storage::disk($disk)->url($path),
            default => $path,
        };
    }

    /**
     * @return BelongsToMany<Lesson, $this>
     */
    public function lessons(): BelongsToMany
    {
        return $this->belongsToMany(Lesson::class)
            ->withPivot(['sort_order', 'note'])
            ->withTimestamps();
    }

    /**
     * Users who have this word in their flashcard deck.
     *
     * @return BelongsToMany<User, $this>
     */
    public function learners(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'user_words')
            ->withPivot(['is_favorite', 'ease_factor', 'interval_days', 'repetitions', 'correct_count', 'wrong_count', 'due_at', 'last_reviewed_at'])
            ->withTimestamps();
    }
}
